language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

addons:
  postgresql: '9.6'

services:
  - postgresql

before_script:
  - mix do ecto.create, ecto.migrate

script:
  - mix do local.hex --force
  - mix deps.get
  - mix test
  - travis_wait mix dialyzer --halt-exit-status

cache:
  directories:
    - priv/plts
